spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/project/h2/jpaapp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: false
    open-in-view: true

logging:
  level:
    org.hiberate.SQL: debug
    org.hiberate.type: trace