spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/project/h2/jpaapp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hiberate.SQL: debug
    org.hiberate.type: trace